### ISSUE TITLE
Can't stub commands

### ISSUE THREAD

**Issue by cromega** [yarmiganosca/shell_mock#3]
Ruby version: 2.5.3p105
gem version: 0.7.0

I'm trying to use this gem to stub Open3.popen2e calls. I enable ShellMock and set it to `dont_let_commands_run` and when I run my test this is what I get:

```
 ShellMock::NoStubSpecified:
       no stub specified for {[:out, :err]=>#<IO:fd 22>}
```

I don't have a stub set up yet so that bit is correct but I'm assuming the error message is not really what it supposed to say.

Also, if I turn off `dont_let_commands_run` I get the following error:

```
  TypeError:
       no implicit conversion of Hash into String
     # /usr/local/bundle/gems/shell_mock-0.7.0/lib/shell_mock/spawn_monkey_patch.rb:26:in `spawn'
     # /usr/local/bundle/gems/shell_mock-0.7.0/lib/shell_mock/spawn_monkey_patch.rb:26:in `override'
```

**Comment by yarmiganosca** [comment]
So I confirmed the second thing you mentioned, and given that the "no stub specified" in the first message is for a hash, I'm assuming they're related. Fix probably today or tomorrow, because that shouldn't be happening.

**Comment by yarmiganosca** [comment]
Interestingly, popen3 and popen2 don't seem to be affected (super weird). Maybe one of those will work instead for your use case until I get the fix in.

**Comment by cromega** [comment]
The problem (or at least part of it) with popen2e is that it passes funny values in `options`. Ater debugging shell_mock a bit this is what I found:

``` 
spawn_monkey_patch.rb:

    11: def override(env, command = nil, options = {})
    12:   command, options = nil, options.merge(command) if command.is_a?(Hash)
    13:   env, command     = {}, env if command.nil?
    14: 
    15:   # other arg manipulation can go here if necessary
    16: 
    17:   stub = StubRegistry.stub_matching(env, command, options)
    18: 
    19:   if stub
    20:     stub.ran
    21: 
    22:     stub.side_effect.call
    23: 
    24:     __un_shell_mocked_spawn(stub.to_oneliner, options)
    25:   else
    26:     if ShellMock.let_commands_run?
    27:       __un_shell_mocked_spawn(env, command, options)
    28:     else
 => 29:       binding.pry
    30:       raise NoStubSpecified.new(env, command, options)
    31:     end
    32:   end
    33: end
```
```
[3] pry(#<ShellMock::SpawnMonkeyPatch>)> options
=> {:in=>#<IO:fd 7>, [:out, :err]=>#<IO:fd 10>}
```

the  `[:out, :err]` array does not work as a keyword argument.

**Comment by yarmiganosca** [comment]
Yup, that is in fact, the exact problem. I just released 0.7.1 (your message reminded me I had finished it Sunday and not released it), which now has a popen2e test, and fixes this problem. Reopen if it persists!

**Comment by cromega** [comment]
Er, I saw your commit and I was using the latest code. I probably should have made it clear. I still have a problem.

if I set `dont_let_commands_run` I get the following error:

```
       wrong number of arguments (given 3, expected 2)
     # ./vendor/shell_mock/lib/shell_mock/no_stub_specified.rb:3:in `initialize'
     # ./vendor/shell_mock/lib/shell_mock/spawn_monkey_patch.rb:27:in `new'
     # ./vendor/shell_mock/lib/shell_mock/spawn_monkey_patch.rb:27:in `override'
```

which happens exactly where the debugging session I pasted is at.

**Comment by yarmiganosca** [comment]
Oh no! My bad. I'll try to take a look after work. Obviously more tests are needed.

**Comment by cromega** [comment]
I submitted a potential fix in #4

**Comment by yarmiganosca** [comment]
Ok, 0.7.2 should fix the `NoStubSpecified` constructor signature issue you're still running into. I also added tests for every Open3 method both with commands allowed to run, and with commands prevented from running, so the test suite should be way better equipped to catch regressions in future. I'll let you close this when you've determined it's fixed.

**Comment by cromega** [comment]
@yarmiganosca It looks good now. Thanks for the quick fix!

**Comment by yarmiganosca** [comment]
No problem! Thanks for bringing to my attention a fundamental inadequacy in
the test suite (no sarcasm; I'm genuinely appreciative)!

Cheers,
Chris Hoffman
